package com.restImie.model;

// Generated 23 juin 2016 13:44:24 by Hibernate Tools 4.0.0

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Delivery generated by hbm2java
 */
@Entity
@Table(name = "rt_delivery", catalog = "Rest")
public class Delivery implements java.io.Serializable {

	private Integer id;
	private String ref;
	private Date date;
	private int orderId;
	private int invoiceId;

	public Delivery() {
	}

	public Delivery(int orderId, int invoiceId) {
		this.orderId = orderId;
		this.invoiceId = invoiceId;
	}

	public Delivery(String ref, Date date, int orderId, int invoiceId) {
		this.ref = ref;
		this.date = date;
		this.orderId = orderId;
		this.invoiceId = invoiceId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ref", length = 45)
	public String getRef() {
		return this.ref;
	}

	public void setRef(String ref) {
		this.ref = ref;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "order_id", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "invoice_id", nullable = false)
	public int getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(int invoiceId) {
		this.invoiceId = invoiceId;
	}

}
