package com.restImie.model;

// Generated 23 juin 2016 13:44:24 by Hibernate Tools 4.0.0

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name = "rt_invoice", catalog = "Rest")
public class Invoice implements java.io.Serializable {

	private Integer id;
	private String ref;
	private Date date;

	public Invoice() {
	}

	public Invoice(String ref, Date date) {
		this.ref = ref;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ref", length = 45)
	public String getRef() {
		return this.ref;
	}

	public void setRef(String ref) {
		this.ref = ref;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
