package com.restImie.model;

// Generated 23 juin 2016 13:44:24 by Hibernate Tools 4.0.0

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Orderdetail generated by hbm2java
 */
@Entity
@Table(name = "rt_orderdetail", catalog = "Rest")
public class Orderdetail implements java.io.Serializable {

	private Integer id;
	private Float amount;
	private int orderId;
	private int productId;

	public Orderdetail() {
	}

	public Orderdetail(int orderId, int productId) {
		this.orderId = orderId;
		this.productId = productId;
	}

	public Orderdetail(Float amount, int orderId, int productId) {
		this.amount = amount;
		this.orderId = orderId;
		this.productId = productId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "amount", precision = 12, scale = 0)
	public Float getAmount() {
		return this.amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	@Column(name = "order_id", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

}
